// Generated by uniffi-bindgen-react-native
#include "react-native-matrix-crypto.h"
#include "generated/matrix_crypto.hpp"

namespace matrixcrypto {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeMatrixCrypto::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}