// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "react-native-matrix-crypto.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "RNNativeModuleSpec.h"

@interface MatrixCrypto : NSObject <NativeMatrixCryptoSpec>
#else
#import <React/RCTBridgeModule.h>

@interface MatrixCrypto : NSObject <RCTBridgeModule>
#endif

@end