#!/usr/bin/env bash
set -euo pipefail

# Spec section 7.2: the bridge has no logger. Generated code is excluded
# because we do not control it; the example app is excluded because it is
# not the bridge.
RUST_HITS=$(grep -rnE '(println!|eprintln!|dbg!|\blog::|\btracing::)' \
  rust/matrix-crypto-core/src rust/matrix-crypto-ffi/src 2>/dev/null || true)

# ubrn also generates src/index.tsx and src/NativeMatrixCrypto.ts, which sit
# directly under src/ rather than inside src/generated/. They must be excluded
# too: a guardrail that fires on tool output nobody controls would block every
# later task. Selected by the absence of the "Generated by
# uniffi-bindgen-react-native" header rather than a hardcoded name list, so any
# future generated file is excluded automatically.
TS_FILES=$(grep -rLE 'Generated by uniffi-bindgen-react-native' \
  --include='*.ts' --include='*.tsx' \
  -r packages/react-native-matrix-crypto/src \
  --exclude-dir=generated 2>/dev/null || true)

TS_HITS=""
if [ -n "$TS_FILES" ]; then
  TS_HITS=$(echo "$TS_FILES" | xargs grep -nE '\bconsole\.[a-z]+' 2>/dev/null || true)
fi

if [ -n "$RUST_HITS$TS_HITS" ]; then
  echo "FAIL: the bridge must not log. Spec section 7.2."
  [ -n "$RUST_HITS" ] && echo "$RUST_HITS"
  [ -n "$TS_HITS" ] && echo "$TS_HITS"
  echo "      Diagnostics belong in a sink the product injects and owns."
  exit 1
fi

echo "PASS: no logger"
