#!/usr/bin/env bash
set -euo pipefail

# Spec section 4bis.3: any drift between the Rust surface and the committed
# generated code is a blocking defect. Regenerate and require an empty diff.
#
# WARNING: do not install `prettier` or `clang-format` as devDependencies
# without checking this gate first. ubrn formats its output with them when
# present ("Skipping formatting C++. Is clang-format installed?" / "No
# prettier found." are printed on every run in this repo today because
# neither is installed) -- adding either would reformat every generated
# file's bytes and fail this gate, for a reason nobody would connect to a
# devDependency bump.
yarn --cwd packages/react-native-matrix-crypto codegen

# NOTE: `ubrn generate jsi turbo-module` writes far more than the two
# `*/generated` directories the original plan assumed. Every path below
# was empirically observed to carry a "Generated by uniffi-bindgen-react-native"
# header, so all of them are drift-checked, not just src/generated and
# cpp/generated. See task-5-report.md controller answer 2 for the full list.
GENERATED_PATHS=(
  packages/react-native-matrix-crypto/src/generated
  packages/react-native-matrix-crypto/cpp/generated
  packages/react-native-matrix-crypto/src/index.tsx
  packages/react-native-matrix-crypto/src/NativeMatrixCrypto.ts
  packages/react-native-matrix-crypto/cpp/react-native-matrix-crypto.cpp
  packages/react-native-matrix-crypto/cpp/react-native-matrix-crypto.h
  packages/react-native-matrix-crypto/android
  packages/react-native-matrix-crypto/ios
  packages/react-native-matrix-crypto/MatrixCrypto.podspec
)

# `git diff` is blind to brand-new untracked files: if a future change to the
# Rust surface makes ubrn emit a file under one of these paths that has never
# been committed before, `git diff --exit-code` below sees nothing to compare
# against and would report PASS. Catch that case explicitly and first, with
# its own message, so it isn't mistaken for the (different) drift case below.
UNTRACKED=$(git status --porcelain -- "${GENERATED_PATHS[@]}" | grep '^??' || true)
if [ -n "$UNTRACKED" ]; then
  echo "FAIL: codegen produced a new file that git isn't tracking yet:"
  echo "$UNTRACKED"
  echo "      git add it and commit, so future drift checks can see it."
  exit 1
fi

if ! git diff --exit-code -- "${GENERATED_PATHS[@]}"; then
  echo "FAIL: generated code is out of date. Run codegen and commit the result."
  echo "      Never hand-edit generated files."
  exit 1
fi

echo "PASS: no codegen drift"
