#!/usr/bin/env bash
set -euo pipefail

# Spec section 7.2: the bridge has no logger. Generated code is excluded
# because we do not control it; the example app is excluded because it is
# not the bridge.

# Derive Rust crate source directories from workspace metadata instead of
# hardcoding them, so new crates added to the workspace are automatically
# covered without editing this script.
RUST_SRC_DIRS=$(cargo metadata --format-version 1 --no-deps \
  --manifest-path rust/Cargo.toml 2>/dev/null \
  | node -e '
      const m = JSON.parse(require("fs").readFileSync(0, "utf8"));
      m.packages.forEach(p => {
        const src = p.manifest_path.replace(/\/Cargo\.toml$/, "/src");
        console.log(src);
      });
    ' 2>/dev/null || printf "rust/matrix-crypto-core/src\nrust/matrix-crypto-ffi/src")

# Verify that we actually got some Rust crate directories. If cargo metadata
# succeeds but produces no output (e.g. due to JSON shape change), RUST_SRC_DIRS
# would be empty, the existence loop below would iterate zero times, and we would
# silently pass having scanned no Rust at all — exactly the failure mode we guard
# against elsewhere.
if [ -z "${RUST_SRC_DIRS// /}" ]; then
  echo "FAIL: could not determine any Rust crate source directories."
  echo "      Refusing to pass having scanned no Rust at all."
  exit 1
fi

# Verify each Rust scan root exists before scanning. A missing root makes
# grep produce an empty result indistinguishable from "no violations found",
# which would silently pass over a moved or deleted crate.
for root in $RUST_SRC_DIRS; do
  if [ ! -d "$root" ]; then
    echo "FAIL: scan root '$root' does not exist."
    echo "      The gate cannot pass over a target that is not there --"
    echo "      if a path moved, update the workspace metadata deliberately."
    exit 1
  fi
done

# Check Rust crates for logging patterns.
# - print! and eprint! are included, not just println!/eprintln!
# - Forbid imports outright (use log::*, use tracing::*) because that
#   prevents bare calls like info!("...") after "use log::info;"
RUST_HITS=$(for root in $RUST_SRC_DIRS; do
  grep -rnE '(println!|eprintln!|print!|eprint!|dbg!|use\s+(log|tracing)::)' "$root" 2>/dev/null || true
done)

PKG_DIR="packages/react-native-matrix-crypto"

# Derive the TypeScript scan roots from package.json's "files" allowlist --
# i.e. from what actually ships -- instead of naming a directory here.
#
# This gate scanned only `src` until 2026-08-28, and `interop/` had by then
# been in "files" for two tasks, carrying 445 lines of library TypeScript that
# nothing ever looked at. There was no violation in it; the rule was simply
# unenforced over half the shipped surface, which is indistinguishable from a
# rule that holds. Deriving the roots means a directory added to "files"
# tomorrow is covered without anyone remembering to come back here.
#
# Negations (`!src/**/*.test.ts`) and globs (`*.aar`, `*.xcframework`,
# `*.podspec`) are skipped: the first remove files rather than name roots, and
# the second name binaries. Test files inside a shipped directory ARE scanned,
# which is what this gate already did for `src`.
TS_ROOTS=$(node -e '
  const fs = require("fs");
  const dir = process.argv[1];
  const pkg = JSON.parse(fs.readFileSync(dir + "/package.json", "utf8"));
  for (const entry of pkg.files || []) {
    if (entry.startsWith("!") || entry.includes("*")) continue;
    const p = dir + "/" + entry;
    if (fs.existsSync(p) && fs.statSync(p).isDirectory()) console.log(p);
  }
' "$PKG_DIR")

# Refuse to pass having scanned nothing: an unreadable package.json, an empty
# "files", or a renamed directory would leave TS_ROOTS empty, the find below
# would return nothing, and this gate would print PASS having read no
# TypeScript at all.
if [ -z "${TS_ROOTS//[[:space:]]/}" ]; then
  echo "FAIL: no shipped TypeScript scan root could be derived from"
  echo "      $PKG_DIR/package.json's \"files\"."
  echo "      Refusing to pass having scanned nothing."
  exit 1
fi

for root in $TS_ROOTS; do
  if [ ! -d "$root" ]; then
    echo "FAIL: scan root '$root' does not exist."
    echo "      The gate cannot pass over a target that is not there."
    exit 1
  fi
done

# For TypeScript/TSX: the bridge may not use console.*.
# uniffi-bindgen-react-native uses two different header conventions:
#   1. // Generated by uniffi-bindgen-react-native
#   2. // This file was autogenerated by some hot garbage in the `uniffi-bindgen-react-native` crate.
# Select files by the absence of "uniffi-bindgen-react-native" in the first
# 3 lines, rather than a hardcoded directory or name list, so any future
# generated file is excluded automatically. The first 3 lines is tight enough
# that no hand-written file in this package mentions the tool name there
# (probe.ts imports from ./generated/matrix_crypto on line 1, which does not
# contain the tool name).
TS_FILES=$(find $TS_ROOTS \
  -type f \( -name '*.ts' -o -name '*.tsx' \) \
  -exec sh -c 'head -3 "$1" | grep -q "uniffi-bindgen-react-native" || echo "$1"' _ {} \;)

# The second half of the "scanned nothing" guard. The roots exist and were
# derived from what ships, but if every file under them were excluded -- or if
# the find above stopped matching -- the grep would return no hits, which is
# byte-for-byte what a clean tree looks like. This package's public entry
# point is TypeScript, so zero hand-written TypeScript files means the scan
# broke, not that the bridge is clean.
if [ -z "${TS_FILES//[[:space:]]/}" ]; then
  echo "FAIL: no hand-written TypeScript was found under: $(echo $TS_ROOTS | tr '\n' ' ')"
  echo "      Refusing to pass having scanned nothing."
  exit 1
fi

TS_HITS=$(echo "$TS_FILES" | xargs grep -nE '\bconsole\.[a-z]+' 2>/dev/null || true)

if [ -n "$RUST_HITS$TS_HITS" ]; then
  echo "FAIL: the bridge must not log. Spec section 7.2."
  [ -n "$RUST_HITS" ] && echo "$RUST_HITS"
  [ -n "$TS_HITS" ] && echo "$TS_HITS"
  echo "      Diagnostics belong in a sink the product injects and owns."
  exit 1
fi

echo "PASS: no logger"
