#!/usr/bin/env bash
set -euo pipefail

# Spec section 4bis.3: any drift between the Rust surface and the committed
# generated code is a blocking defect. Regenerate and require an empty diff.
yarn --cwd packages/react-native-matrix-crypto codegen

# NOTE: `ubrn generate jsi turbo-module` writes far more than the two
# `*/generated` directories the original plan assumed. Every file below
# was empirically observed to carry a "Generated by uniffi-bindgen-react-native"
# header, so all of them are drift-checked, not just src/generated and
# cpp/generated. See task-5-report.md controller answer 2 for the full list.
if ! git diff --exit-code -- \
     packages/react-native-matrix-crypto/src/generated \
     packages/react-native-matrix-crypto/cpp/generated \
     packages/react-native-matrix-crypto/src/index.tsx \
     packages/react-native-matrix-crypto/src/NativeMatrixCrypto.ts \
     packages/react-native-matrix-crypto/cpp/react-native-matrix-crypto.cpp \
     packages/react-native-matrix-crypto/cpp/react-native-matrix-crypto.h \
     packages/react-native-matrix-crypto/android \
     packages/react-native-matrix-crypto/ios \
     packages/react-native-matrix-crypto/MatrixCrypto.podspec; then
  echo "FAIL: generated code is out of date. Run codegen and commit the result."
  echo "      Never hand-edit generated files."
  exit 1
fi

echo "PASS: no codegen drift"
