#!/usr/bin/env bash
set -euo pipefail

# ONE question, answered ONCE, for every gate that needs it: which committed
# files in this repository are generated code?
#
# Two answers to that question already existed and were never compared:
#
#   ORACLE A  scripts/generated-paths.txt, expanded through `git ls-files` --
#             "it is generated because it sits under a path we listed".
#             assert-no-drift.sh regenerates these, and assert-no-logger.sh
#             exempts them from parts of the no-logger rule.
#
#   ORACLE C  the tool's own header in the first three lines --
#             "it is generated because it says so".
#             assert-generated-not-stubbed.sh enumerates its artifacts this
#             way, because it has to run in the build jobs where codegen
#             cannot.
#
# M1's final review (item C9) closed the case where the header oracle was
# forged by TYPING THE HEADER INTO A FILE, by moving assert-no-logger.sh onto
# the path list. The 2026-08-28 verification-infrastructure review found the
# mirror image still open: forge the PATH oracle instead, by putting a
# hand-written file in a listed DIRECTORY. Reproduced before this script was
# written -- a tracked, prettier-formatted
# `src/generated/review-helper.ts` containing `console.log('PLAINTEXT ' +
# plaintext)`:
#
#     gate:logger  PASS  "no logger"                     (exempted by prefix)
#     gate:drift   PASS  "no codegen drift (9 paths ...)" (git diff is silent:
#                                                          codegen never
#                                                          DELETES what it
#                                                          does not emit, and
#                                                          the file is
#                                                          tracked, so the
#                                                          untracked guard
#                                                          does not apply)
#     gate:stubs   PASS  "...(19 artifacts...)"          (no header, so never
#                                                          enumerated)
#
# `files: ["src"]` ships that file. The comment in assert-no-logger.sh that
# said a tolerated write "cannot have been planted by hand without gate:drift
# failing first" was false for ADDED files, and this script is what makes it
# true.
#
# The fix is the cross-check the no-logger-generated-cpp report proposed and
# did not make: the two oracles must select the SAME set, in both directions.
# A hand-planted file is in A and not in C. A header-stripped, hollowed-out
# artifact drops out of C while staying in A -- which is the same review's
# "the artifact set shrank 19 -> 18 in silence". A generated file emitted at a
# path nobody listed is in C and not in A, and gate:drift would never
# regenerate it.
#
# Contract: on success this prints the agreed set to STDOUT, one repository-
# relative path per line, sorted, and exits 0. Every diagnostic goes to
# STDERR, so a caller may capture the set with $(...) and still have its
# failures reach the log.

err() { echo "$@" >&2; }

# `comm` compares two streams that must be sorted in the SAME order it
# collates in. Under a UTF-8 locale macOS and GNU sort disagree with each
# other about case and punctuation, and `comm` then reports differences that
# are not there. Pin the collation so this script says the same thing on a
# developer's machine and on the runner.
export LC_ALL=C

GENERATED_PATHS_FILE="scripts/generated-paths.txt"

# The root the header sniff sweeps. Every listed path must live inside it --
# asserted below rather than assumed, because a listed path outside this root
# would be regenerated by gate:drift and yet never cross-checked here, which
# is precisely the kind of silent under-coverage this script exists to end.
PKG="packages/react-native-matrix-crypto"

if [ ! -f "$GENERATED_PATHS_FILE" ]; then
  err "FAIL: $GENERATED_PATHS_FILE is missing."
  err "      It is one of the two oracles this cross-check compares; without"
  err "      it nothing here can be decided."
  exit 1
fi

PREFIXES=()
while IFS= read -r ln; do
  ln="${ln%%#*}"
  ln="$(printf '%s' "$ln" | tr -d '[:space:]')"
  [ -n "$ln" ] || continue
  PREFIXES+=("$ln")
done < "$GENERATED_PATHS_FILE"

if [ "${#PREFIXES[@]}" -eq 0 ]; then
  err "FAIL: $GENERATED_PATHS_FILE lists no paths."
  err "      Refusing to pass with an exemption list nobody wrote."
  exit 1
fi

for p in "${PREFIXES[@]}"; do
  case "$p" in
    "$PKG" | "$PKG"/*) ;;
    *)
      err "FAIL: generated path '$p' is outside $PKG."
      err "      The header sweep below only reads committed files under"
      err "      $PKG, so a path outside it would be regenerated by"
      err "      gate:drift and never cross-checked here. Widen PKG in"
      err "      scripts/generated-file-set.sh deliberately."
      exit 1
      ;;
  esac
done

# Committed files only, on both sides. The build jobs run gate:stubs on a tree
# that also holds gradle and CMake output carrying the same header (e.g.
# android/build/intermediates/.../proguard.txt); none of that is an artifact
# anyone ships or reviews, and none of it is tracked.
TRACKED=$(git ls-files -- "$PKG")

if [ -z "${TRACKED//[[:space:]]/}" ]; then
  err "FAIL: refusing to pass having scanned nothing."
  err "      git ls-files reported no committed file under $PKG."
  exit 1
fi

BY_PATH=""
BY_HEADER=""
while IFS= read -r f; do
  [ -n "$f" ] || continue
  [ -f "$f" ] || continue

  for p in "${PREFIXES[@]}"; do
    case "$f" in
      "$p" | "$p"/*) BY_PATH="${BY_PATH}${f}"$'\n'; break ;;
    esac
  done

  # The same three-line window assert-generated-not-stubbed.sh has always
  # used. Three lines is tight enough that hand-written files which
  # legitimately name the tool further down (README.md, scripts/codegen.sh,
  # package.json) are not selected.
  if awk '
      NR <= 3 && /uniffi-bindgen-react-native/ { found = 1 }
      NR > 3 { exit }
      END { exit(found ? 0 : 1) }
    ' "$f" 2>/dev/null; then
    BY_HEADER="${BY_HEADER}${f}"$'\n'
  fi
done <<< "$TRACKED"

BY_PATH=$(printf '%s' "$BY_PATH" | sort)
BY_HEADER=$(printf '%s' "$BY_HEADER" | sort)

# Refuse to pass having compared nothing. Two empty sets agree perfectly.
if [ -z "${BY_PATH//[[:space:]]/}" ]; then
  err "FAIL: refusing to pass having compared nothing."
  err "      No committed file lies under any path in $GENERATED_PATHS_FILE."
  exit 1
fi
if [ -z "${BY_HEADER//[[:space:]]/}" ]; then
  err "FAIL: refusing to pass having compared nothing."
  err "      No committed file under $PKG carries a"
  err "      uniffi-bindgen-react-native header in its first 3 lines, which"
  err "      means the sniff broke rather than that the tree is clean."
  exit 1
fi

PLANTED=$(comm -23 <(printf '%s\n' "$BY_PATH") <(printf '%s\n' "$BY_HEADER"))
UNLISTED=$(comm -13 <(printf '%s\n' "$BY_PATH") <(printf '%s\n' "$BY_HEADER"))

if [ -n "$PLANTED" ]; then
  err "FAIL: a committed file sits under a generated path but is not generated"
  err "      code -- it does not carry the generator's header:"
  err "$PLANTED"
  err "      Either the generator did not write it, in which case it is a"
  err "      hand-written file claiming an exemption it has not earned and"
  err "      must move out of the generated directory, or it is a real"
  err "      artifact that has been hollowed out and lost its header, in"
  err "      which case regenerate with"
  err "      'yarn --cwd $PKG codegen' and commit the result."
  exit 1
fi

if [ -n "$UNLISTED" ]; then
  err "FAIL: a committed file carries the generator's header but lies under no"
  err "      path in $GENERATED_PATHS_FILE:"
  err "$UNLISTED"
  err "      gate:drift never regenerates it and gate:logger never exempts"
  err "      it. If the generator really emits it, add its path to"
  err "      $GENERATED_PATHS_FILE. If it does not, delete it."
  exit 1
fi

printf '%s\n' "$BY_PATH"
